### ISSUE TITLE
Use a table, using ids instead of a list in kwin-block-windows

### ISSUE THREAD

**Issue by noahdotpy** [noahdotpy/idwt#10]
New:
```yaml
kwin-block-windows:
  block-pip:
    title:
      value: "Picture-in-picture"
      match_type: exact
```

the id will also be used in the description
