### ISSUE TITLE
restructure user-networking

### ISSUE THREAD

**Issue by noahdotpy** [noahdotpy/idwt#12]
```yaml
networking:
  mode: schedule
  schedule: schedule1
  schedules:
    schedule1:
      days_allowed: [monday, tuesday, wednesday, thursday, friday]
      allow_start: 8:30 # time to start allowing internet
      allow_end: 18:00 # time to stop allowing internet

```
