### ISSUE TITLE
add a block otherwise for `disconnect-flatpak-apps`

### ISSUE THREAD

**Issue by noahdotpy** [noahdotpy/idwt#15]
This is likely to have to be done by getting a list of app ids. This can be done by `flatpak list --columns app | tail -n +1 | split row "\n"`. This will also have to be done *as the user* somehow (`/usr/bin/su`?, this could also be done by listing all files in `~/.local/share/flatpak/exports/bin/` and adding this to the output of `flatpak list --system # and the rest of the command...`).

This list can then be used to disallow all apps that aren't allowed. This would be done by removing all allowed apps from the list and then creating the override files to disable networking for that app.

```yaml
flatpak-app-networking:
  allow-only: # when allow-only is populated then only these apps are allowed
    - com.spotify.Client
  block:
    - com.discordapp.Discord
```
