### ISSUE TITLE
config parsing does not do deep merging.

### ISSUE THREAD

**Issue by noahdotpy** [noahdotpy/idwt#22]
pretend this:
```yaml
# /etc/idwt/config.yml
tightener:
  delay: 90
```
```yaml
# /usr/share/idwt/default-config.yml
tightener:
  approved-commands:
    - ^config \.block-sites \+= \["[^"']*"\]$
    - ^config \.flatpak-app-networking\.allow-only -= \["[^"']*\.[^"']*\.[^"']*"\]$
    - ^config \.flatpak-app-networking\.block \+= \["[^"']*\.[^"']*\.[^"']*"\]$
    - ^config \.networking\.mode = "block"$
    - ^group remove [^\s]* wheel$
    - ^make_file_immutable .*$
    - ^config \.tightener\.delay \+= [0-9]*$
```
then the result will be 
```yaml
tightener:
  delay: 90
```
