### ISSUE TITLE
Allow binaries that have a specific sha256sum

### ISSUE THREAD

**Issue by noahdotpy** [noahdotpy/idwt#25]
```yaml
binary-killing:
    block:
        # ...
    allow:
        9abdjwuzhebdjs8273ubdsu72
```
