### ISSUE TITLE
Make every separate argument of the tightened command match with a regex

### ISSUE THREAD

**Issue by noahdotpy** [noahdotpy/idwt#26]
```yml
tightener:
    approved-commands:
        - ["^group$", "^remove$", "^[^\s]*$", "^wheel$"]
```
