### ISSUE TITLE
add generic `.when` key to handle scheduling

### ISSUE THREAD

**Issue by noahdotpy** [noahdotpy/idwt#28]
```yml
when:
  - schedule:
      monday: # apply rule on mondays between 7:00 (7am) - 18:00 (6pm)
        start: 07:00
        end: 18:00
      tuesday-friday: # apply rule on tuesday, wednesday, thursday between midnight (start of day) and 5pm
        start: 00:00
        end: 17:00
      saturday,sunday: # apply rule on saturday and sunday all day
        start: 00:00
        end: # whatever midnight would be (24:00??)
      # if time is not specified as time to apply then the rule will not be applied
    rule:
      networking:
        mode: allow
```
